import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:islami/my_theme_data.dart';
import '../models/sura_model.dart';
import '../sura_details.dart';

class QuranTab extends StatelessWidget {
  QuranTab({super.key});

  List<String> suraNames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> englishSuraNames = [
    "Al-Fatihah",
    "Al-Baqarah",
    "Al-Imran",
    "Al-Nisa",
    "Al-Ma'idah",
    "Al-An`am",
    "Al-A`raf",
    "Al-Anfal",
    "Al-Taubah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Al-Ra`d",
    "Ibrahim",
    "Al-Hijr",
    "Al-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "TaHa",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "Al-Nur",
    "Al-Furqan",
    "Al-Shu`ara",
    "Al-Naml",
    "Al-Qasas",
    "Al-`Ankabut",
    "Al-Rum",
    "Luqman",
    "Al-Sajdah",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "YaSin",
    "Al-Saffat",
    "Sad",
    "Al-Zumar",
    "Ghafir",
    "Fussilat",
    "Al-Shura",
    "Al-Zukhruf",
    "Al-Dukhan",
    "Al-Jathiyah",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Al-Dhariyat",
    "Al-Tur",
    "Al-Najm",
    "Al-Qamar",
    "Al-Rahman",
    "Al-Waqi`ah",
    "Al-Hadid",
    "Al-Mujadilah",
    "Al-Hashr",
    "Al-Mumtahanah",
    "Al-Saff",
    "Al-Jumu`ah",
    "Al-Munafiqun",
    "Al-Taghabun",
    "Al-Talaq",
    "Al-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma`arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzammil",
    "Al-Mudathir",
    "Al-Qiyamah",
    "Al-Insane",
    "Al-Mursalat",
    "Al-Naba",
    "Al-Nazi`at",
    "Abasa",
    "Al-Takwir",
    "Al-Infitar",
    "Al-Mutaffifeen",
    "Al-Inshiqaq",
    "Al-Buruj",
    "Al-Tariq",
    "Al-A`la",
    "Al-Ghashiya",
    "Al_Fajr",
    "Al-Balad",
    "Al-Shams",
    "Al-Layl",
    "Al-Duha",
    "Al-Sharh",
    "Al-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyinah",
    "Al-Zalzala",
    "Al-Adiyat",
    "Al-Qari`ah",
    "Al-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraish",
    "Al-Ma`un",
    "Al-Kauthar",
    "Al-Kafirun",
    "Al-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "Al-Nas",
  ];
  List<int> versesNumber = [
    7,
    286,
    200,
    176,
    120,
    165,
    206,
    75,
    129,
    109,
    123,
    111,
    43,
    52,
    99,
    128,
    111,
    110,
    98,
    135,
    112,
    78,
    118,
    64,
    77,
    227,
    93,
    88,
    69,
    60,
    34,
    30,
    73,
    54,
    45,
    83,
    182,
    88,
    75,
    85,
    54,
    53,
    89,
    59,
    37,
    35,
    38,
    29,
    18,
    45,
    60,
    49,
    62,
    55,
    78,
    96,
    29,
    22,
    24,
    13,
    14,
    11,
    11,
    18,
    12,
    12,
    30,
    52,
    52,
    44,
    28,
    28,
    20,
    56,
    40,
    31,
    50,
    40,
    46,
    42,
    29,
    19,
    36,
    25,
    22,
    17,
    19,
    26,
    30,
    20,
    15,
    21,
    11,
    8,
    5,
    19,
    5,
    8,
    8,
    11,
    11,
    8,
    3,
    9,
    5,
    4,
    6,
    3,
    6,
    3,
    5,
    4,
    5,
    6
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Image.asset(
          "assets/images/qur2an_screen_logo.png",
          height: 227,
          width: double.infinity,
        ),
        Table(
          border: TableBorder(
            top: BorderSide(
              color: MyThemeData.primaryColor,
              width: 3.0,
            ),
            bottom: BorderSide(
              color: MyThemeData.primaryColor,
              width: 3.0,
            ),
            verticalInside: BorderSide(
              color: MyThemeData.primaryColor,
              width: 3.0,
            ),
          ),
          children: <TableRow>[
            TableRow(
              children: <TableCell>[
                TableCell(
                  child: Container(
                    height: 45.0,
                    alignment: Alignment.center,
                    child: Text(
                      "sura_name".tr(),
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                  ),
                ),
                TableCell(
                  child: Container(
                    height: 45.0,
                    alignment: Alignment.center,
                    child: Text(
                      "verses_number".tr(),
                      textAlign: TextAlign.center,
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
        Expanded(
          child: ListView.builder(
            itemCount: suraNames.length,
            itemBuilder: (context, index) {
              return GestureDetector(
                onTap: () {
                  Navigator.pushNamed(
                    context,
                    SuraDetails.routeName,
                    arguments: SuraModel(
                      suraName: suraNames[index],
                      suraIndex: index,
                    ),
                  );
                },
                child: Row(
                  children: [
                    Expanded(
                      child: Text(
                        context.locale == Locale("ar")
                            ? suraNames[index]
                            : englishSuraNames[index],
                        textAlign: TextAlign.center,
                        style: Theme.of(context).textTheme.bodyLarge,
                      ),
                    ),
                    Container(
                      height: 45.0,
                      width: 3.0,
                      color: MyThemeData.primaryColor,
                    ),
                    Expanded(
                      child: Text(
                        versesNumber[index].toString(),
                        textAlign: TextAlign.center,
                        style: Theme.of(context).textTheme.bodyLarge,
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}
